Added 8LED display (blinkt) and emulator
tech-time/build-box pull request #1
Opened 2017-08-23 11:46 UTC by Guy-1xx1

2017-08-23 15:10 UTC, rbnxx requested changes
j'ai mis les commentaires de ce midi par écrit

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/buildbox.py
> +from .devices import DigitalDisplay, GraphicDisplay, LEDDisplay
LEDDisplay => RGBLeds (le cas échéant LedBar, RGBLedBarDisplay, RGBLedsBarDisplay, mais j'ai une préférence pour RGBLeds)

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/buildbox.py
> +    ld = LEDDisplay()
LEDDisplay() => RGBLeds()

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/buildbox.py
> +        ld.show()
j'aurais tendance à masquer la fonction "show" de l'API blinkt dans RGBLeds... au moins dans un premier temps (à voir si on a vraiment besoin de bufferiser les MAJ des leds).

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/buildbox.py
> +        gd.displaytext(2, 2, 'Job: '+ bi.name)
Pour info, je vais faire évoluer le "displaytext" pour un fonctionnement plus haut niveau afin de faciliter la vie des utilisateurs du LCD (réflexion en cours)

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/buildbox.py
> +        if 0  <= bi.status <= 50:  r, g, b = 255,   0,  0
cette logique parait réutilisable, à voir si on veut la mettre dans un module "utils" ou directement dans RGBLeds.

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/builds.py
> +class Builds(Thread):
Builds.Builds... que dirais-tu de continuousintegration.Jobs
Il n'y a pas que des "Builds" au sens propre, mais des Jobs (de deploiement par exemple).
Si tu trouve mieux que "continuousintegration", je suis preneur ( ci.Jobs ?)

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/builds.py
> +        self._builds_ = [ Builditem(15, 50, "job1"),
pour un attribut privé, pas besoin de mettre de '_' à la fin: self._builds

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/builds.py
> +        self._index_=0
pour un attribut privé, pas besoin de mettre de '_' à la fin: self._index

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/devices/ledbar.py
> +'''
Il faudrait discuter un peu de la meilleure façon de reorganiser cette partie.
Pour l'afficheur 7 segments, j'ai fait un leddigits et un leddigitssimulator, pour le OLED, j'ai une classe principale GraphicsDisplay qui génère une image qui va soit sur l'afficheur, soit sur la fenetre TK (l'API est commune à l'émulateur et à l'afficheur). 
Dans le cas de la barre de led, il faut voir...  ce qui est le mieux. (dans l'absolu, il faudrait virer le code de pimoroni sans le dupliquer.

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/devices/ledbarsimulator.py
> +class LEDDisplaySimulator():
Finalement, cette classe LEDDisplaySimulator pourrit devenir RGBLeds et fonctionner en mode normal ou simulé (comme pour GraphicsDisplay):

si "from blinkt import set_pixel, show" génère une exception, on passe en mode émulation
A chaque méthode (il n'y en a pas beaucoup), selon qu'on est est en mode émulation ou non, soit on envoit une demande de rafraichissement à bboxemu, soit on utilise l'api blinkt pour modifier les leds...

2017-08-23 15:10 UTC, rbnxx commented on src/buildbox/devices/leddigits.py
> +        pi7seg.init(data_pin, clock_pin, latch_pin, registers, no_of_displays, common_cathode_type)
Ca passe le PEP8 80 caractères de large ça? ;)

2017-09-13 11:17 UTC, Guy-1xx1 commented on src/buildbox/devices/ledbarsimulator.py
> +class LEDDisplaySimulator():
La classe LEDDisplaySimulator a disparu, remplacé par RGBLeds dans laquel l'import de blinkt, si elle échoue met un flag rgbledsemulate à Vrai et ensuite, pour chaque méthode, seleon ce flag, on émule ou on renvoie vers blinkt.

2017-09-13 11:18 UTC, Guy-1xx1 commented on src/buildbox/devices/ledbar.py
> +'''
Il n'y a plus qu'une classe qui appelle (ou non) le code de blinkt.

2017-09-13 11:19 UTC, Guy-1xx1 commented on src/buildbox/builds.py
> +        self._index_=0
Fait

2017-09-13 11:19 UTC, Guy-1xx1 commented on src/buildbox/builds.py
> +        self._builds_ = [ Builditem(15, 50, "job1"),
Fait

2017-09-13 11:21 UTC, Guy-1xx1 commented on src/buildbox/builds.py
> +class Builds(Thread):
Fait

2017-09-13 11:24 UTC, Guy-1xx1 commented on src/buildbox/buildbox.py
> +        if 0  <= bi.status <= 50:  r, g, b = 255,   0,  0
C'est le code qui indique comment afficher sur les périphériques les données des jobs: ce n'est ni du domaine des jobs, ni du domaine des périphériques (.devices). Pour l'instant je le laisse là.

2017-09-13 11:28 UTC, Guy-1xx1 commented on src/buildbox/buildbox.py
> +        ld.show()
J'ai remplacé le show() par displayleds().
comme ça chaque périphérique affiche via une méthode displayXXX.

2017-09-13 11:28 UTC, Guy-1xx1 commented on src/buildbox/buildbox.py
> +    ld = LEDDisplay()
Fait

2017-09-13 11:28 UTC, Guy-1xx1 commented on src/buildbox/buildbox.py
> +from .devices import DigitalDisplay, GraphicDisplay, LEDDisplay
J'ai tout changé en RGBLeds.

2017-09-20 10:35 UTC, merged